# Generated by Django 2.1.7 on 2019-03-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='full_description',
            field=models.TextField(blank=True, default=None, help_text='The full description of what the thing is', null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='short_description',
            field=models.CharField(blank=True, default=None, help_text='A roughly one-breath sentence that describes the thing', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(default=None, help_text='The abstract parent class for all reference lookup types', max_length=255, unique=True),
        ),
    ]
