# Generated by Django 2.1.7 on 2019-03-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0002_auto_20190319_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='cast_time',
            field=models.CharField(blank=True, default=None, help_text='How long it takes to cast the spell', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='components',
            field=models.CharField(blank=True, default=None, help_text='Whatever spell components are necessary to cast the spell', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='is_concentration',
            field=models.BooleanField(default=False, help_text='Whether the spell requires concentration or not'),
        ),
        migrations.AddField(
            model_name='spell',
            name='is_ritual',
            field=models.BooleanField(default=False, help_text='Whether the spell can be cast as a ritual or not'),
        ),
        migrations.AddField(
            model_name='spell',
            name='school',
            field=models.CharField(blank=True, default=None, help_text='What spell school this belongs to, e.g. evocation or conjuration', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='source',
            field=models.CharField(blank=True, default=None, help_text='If applicable, the original source for this', max_length=255, null=True),
        ),
    ]
