# Generated by Django 2.1.7 on 2019-03-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0003_auto_20190319_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='The abstract parent class for all reference lookup types', max_length=255, unique=True)),
                ('short_description', models.CharField(blank=True, default=None, help_text='A roughly one-breath sentence that describes the thing', max_length=255, null=True)),
                ('full_description', models.TextField(blank=True, default=None, help_text='The full description of what the thing is', null=True)),
                ('source', models.CharField(blank=True, default=None, help_text='If applicable, the original source for this', max_length=255, null=True)),
                ('type', models.CharField(blank=True, default=None, help_text='A classification for grouping like items together, e.g. weapons or kits or glasses', max_length=255, null=True)),
                ('rarity', models.CharField(blank=True, default='Common', help_text='The tier of rarity assigned to this item', max_length=255, null=True)),
                ('requires_attunment', models.BooleanField(default=False, help_text='Whether the item requires attunement before it can be fully utilized')),
                ('weight', models.FloatField(blank=True, default=0.0, help_text='The numeric weight of the item (in whatever units you care to use)')),
                ('weight_units', models.CharField(blank=True, default='pounds', help_text="The default unit associated with the item's weight", max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
