# Generated by Django 2.1.7 on 2019-03-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='duration',
            field=models.CharField(blank=True, default='Instantaneous', help_text='How long the spell lasts', max_length=255, null=True),
        ),
    ]
